expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.IP.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
notary:
  enabled: false

harborAdminPassword: "admin" 